export const POLICIES = [
    // --- เพื่อไทย (PTP) ---
    { id: 101, party: "PTP", cat: "economy", title: "Digital Economy & รัฐร่วมจ่าย", desc: "ยกระดับ Digital Wallet เป็นโครงสร้างพื้นฐานดิจิทัล รัฐช่วยจ่าย 70% ประชาชน 30% กระตุ้น GDP ครั้งใหญ่", ref: "Nation Debate", url: "https://www.youtube.com/live/mUTZk_DtlrM", verify: true },
    { id: 102, party: "PTP", cat: "economy", title: "ประกันกำไรเกษตรกร 30%", desc: "เปลี่ยนจากประกันราคา เป็นประกัน 'กำไร' ให้เกษตรกร 30% ของต้นทุนการผลิต", ref: "The Standard Economic Battle", url: "https://www.youtube.com/@TheStandardNews", verify: true },
    { id: 103, party: "PTP", cat: "education", title: "Wellness Economy Hub", desc: "สร้างงานสร้างรายได้จากเศรษฐกิจสุขภาพครบวงจรและนวัตกรรมการแพทย์ ดึงเม็ดเงินจากต่างชาติ", ref: "วิสัยทัศน์ ดร.ยศชนัน", url: "https://ptp.or.th", verify: true },
    { id: 104, party: "PTP", cat: "politics", title: "Blockchain Government", desc: "ใช้เทคโนโลยี Blockchain จัดการข้อมูลภาครัฐ ลดความซ้ำซ้อนและป้องกันการทุจริตอย่างโปร่งใส", ref: "ยุทธศาสตร์พรรค", url: "https://ptp.or.th", verify: true },
    { id: 105, party: "PTP", cat: "social", title: "30 บาท AI", desc: "ยกระดับ 30 บาทรักษาทุกโรคด้วย AI และ Telemedicine เชื่อมโยงข้อมูลสุขภาพทั่วประเทศ", ref: "Thai PBS Policy Watch", url: "https://thaipbs.or.th/election69", verify: true },
    { id: 106, party: "PTP", cat: "economy", title: "รถไฟฟ้า 20 บาทตลอดสาย", desc: "สานต่อนโยบายรถไฟฟ้า 20 บาทให้ครอบคลุมทุกสี ทุกเส้นทาง เพื่อลดค่าครองชีพคนเมือง", ref: "นโยบายคมนาคม", url: "https://ptp.or.th", verify: true },
    { id: 107, party: "PTP", cat: "social", title: "สิทธิความหลากหลายทางเพศ", desc: "ผลักดันกฎหมายรับรองอัตลักษณ์ทางเพศและสวัสดิการข้ามเพศ", ref: "เวที Pride Vote", url: "https://www.youtube.com/playlist?list=PLR2sF1qc48QSVbFJnJbWFrUC8rsP", verify: true },
    { id: 108, party: "PTP", cat: "education", title: "Learn to Earn", desc: "เรียนรู้มีรายได้ จบ ป.ตรี อายุ 18 ปี ปรับระบบการศึกษาให้ยืดหยุ่น", ref: "นโยบายการศึกษา", url: "https://ptp.or.th", verify: true },
    { id: 109, party: "PTP", cat: "education", title: "โรงเรียน 2 ภาษา", desc: "สอนภาษาอังกฤษ/จีน ตั้งแต่ ป.1 ทุกท้องถิ่น", ref: "นโยบายการศึกษา", url: "https://ptp.or.th", verify: true },
    { id: 110, party: "PTP", cat: "security", title: "วีซ่าฟรีทั่วโลก (Visa Free)", desc: "เจรจาวีซ่าฟรีกับกลุ่มประเทศเชงเก้นและพันธมิตร เพื่อส่งเสริมการท่องเที่ยวและธุรกิจ", ref: "วิสัยทัศน์นายกฯ", url: "https://ptp.or.th", verify: true },
    { id: 111, party: "PTP", cat: "environment", title: "พ.ร.บ.อากาศสะอาด", desc: "ผลักดันกฎหมายอากาศสะอาดฉบับบูรณาการ คืนสิทธิในการหายใจให้ประชาชน", ref: "แถลงการณ์พรรค", url: "https://ptp.or.th", verify: true },
    { id: 112, party: "PTP", cat: "environment", title: "Net Zero 2050", desc: "มุ่งสู่ความเป็นกลางทางคาร์บอนภายในปี 2050 ด้วยเศรษฐกิจสีเขียวและ Carbon Credit", ref: "วิสัยทัศน์สิ่งแวดล้อม", url: "https://ptp.or.th", verify: true },

    // --- ประชาชน (PP) ---
    { id: 201, party: "PP", cat: "social", title: "สวัสดิการถ้วนหน้าครบวงจร", desc: "เงินเด็กเล็ก 600 บาท, ผู้สูงอายุ 1,000 บาท ให้ทุกคนโดยไม่ต้องพิสูจน์ความจน เริ่ม 1 ต.ค. 69", ref: "เว็บไซต์พรรค / Debate", url: "https://peoplesparty.or.th", verify: true },
    { id: 202, party: "PP", cat: "economy", title: "หวยใบเสร็จ", desc: "นำใบกำกับภาษีร้านค้ารายย่อยมาชิงโชคทุกเดือน ดึง SME เข้าระบบและกระตุ้นยอดขายฐานราก", ref: "White Paper", url: "https://election69.peoplesparty.or.th/policy/", verify: true },
    { id: 203, party: "PP", cat: "politics", title: "จังหวัดจัดการตนเอง", desc: "ยุติรัฐราชการรวมศูนย์ กระจายอำนาจและงบประมาณ เลือกตั้งผู้ว่าฯ ทุกจังหวัดทั่วประเทศ", ref: "The Standard Battle", url: "https://www.youtube.com/@TheStandardNews", verify: true },
    { id: 204, party: "PP", cat: "education", title: "คืนครูให้นักเรียน", desc: "ลดภาระงานเอกสารครู ยกเลิกพิธีกรรมที่ไม่จำเป็น ปฏิรูปหลักสูตรให้ทันสมัย", ref: "เว็บไซต์พรรค", url: "https://peoplesparty.or.th", verify: true },
    { id: 205, party: "PP", cat: "economy", title: "ทลายทุนผูกขาด", desc: "แก้กฎหมายแข่งขันทางการค้า เปิดเสรีสุราและพลังงาน ลดค่าครองชีพประชาชน", ref: "เวทีปราศรัยใหญ่", url: "https://peoplesparty.or.th", verify: true },
    { id: 206, party: "PP", cat: "security", title: "ยกเลิกเกณฑ์ทหาร", desc: "เปลี่ยนเป็นระบบสมัครใจ 100% สร้างทหารอาชีพ ลดจำนวนนายพล", ref: "นโยบายพรรค", url: "https://peoplesparty.or.th", verify: true },
    { id: 207, party: "PP", cat: "social", title: "สมรสเท่าเทียมทันที", desc: "ผลักดันกฎหมายสมรสเท่าเทียมให้ผ่านสภาและบังคับใช้ภายใน 100 วันแรก", ref: "เวที Pride Vote", url: "https://www.youtube.com/playlist?list=PLR2sF1qc48QSVbFJnJbWFrUC8rsP", verify: true },
    { id: 208, party: "PP", cat: "economy", title: "Strategic Industries", desc: "สร้างห่วงโซ่อุปทานใหม่ในอุตสาหกรรมยุทธศาสตร์ เพื่อแข่งขันในเวทีโลก", ref: "เวที FCCT", url: "https://www.youtube.com/watch?v=L2wL6jkUrqY", verify: true },
    { id: 209, party: "PP", cat: "education", title: "Free Education+", desc: "เรียนฟรีจริง อาหารกลางวันฟรี รถรับส่งฟรี", ref: "นโยบายการศึกษา", url: "https://peoplesparty.or.th", verify: true },
    { id: 210, party: "PP", cat: "education", title: "โรงเรียนประชาธิปไตย", desc: "ปฏิรูปกฎระเบียบทรงผม/เครื่องแบบ เคารพสิทธิมนุษยชน", ref: "นโยบายการศึกษา", url: "https://peoplesparty.or.th", verify: true },
    { id: 211, party: "PP", cat: "security", title: "การทูตเชิงคุณค่า", desc: "นำไทยกลับสู่เวทีโลกด้วยจุดยืนประชาธิปไตยและสิทธิมนุษยชน (ASEAN Leadership)", ref: "White Paper", url: "https://election69.peoplesparty.or.th/policy/", verify: true },
    { id: 212, party: "PP", cat: "environment", title: "พ.ร.บ.โลกร้อน (Climate Change Bill)", desc: "กำหนดเพดานการปล่อยก๊าซเรือนกระจก (Cap & Trade) และกองทุนปรับตัวรับมือภัยพิบัติ", ref: "Policy Fest", url: "https://peoplesparty.or.th", verify: true },
    { id: 213, party: "PP", cat: "environment", title: "รถเมล์ไฟฟ้าทุกจังหวัด", desc: "เปลี่ยนรถขนส่งสาธารณะเป็น EV ทั่วประเทศภายใน 7 ปี ลดมลพิษในเมือง", ref: "นโยบายขนส่ง", url: "https://peoplesparty.or.th", verify: true },

    // --- รวมไทยสร้างชาติ (UTN) ---
    { id: 301, party: "UTN", cat: "politics", title: "ประหารชีวิตคนโกง", desc: "เพิ่มโทษสูงสุดประหารชีวิตสำหรับคดีทุจริตคอร์รัปชัน และอาชญากรรมทางเศรษฐกิจรุนแรง", ref: "Nation Debate (อรรถวิชช์)", url: "https://www.youtube.com/live/mUTZk_DtlrM", verify: true },
    { id: 302, party: "UTN", cat: "security", title: "ยกเลิก MOU44", desc: "ยกเลิก MOU44 ทางทะเล และสร้างรั้วชายแดนเพื่อความชัดเจนของเขตแดนและอธิปไตย", ref: "Nation Debate", url: "https://www.youtube.com/live/mUTZk_DtlrM", verify: true },
    { id: 303, party: "UTN", cat: "economy", title: "รื้อโครงสร้างพลังงาน", desc: "ลดค่าไฟและตรึงราคาน้ำมัน/แก๊ส ด้วยการรื้อสัญญาสัมปทานและโครงสร้างราคาใหม่", ref: "The Standard Economic Battle", url: "https://www.youtube.com/@TheStandardNews", verify: true },
    { id: 304, party: "UTN", cat: "security", title: "ทหารอาสา เงินเดือน 30k", desc: "เงินเดือนทหารเกณฑ์สมัครใจ 30,000 บาท และโบนัสออกรบ สร้างแรงจูงใจ", ref: "Nation Debate", url: "https://www.youtube.com/live/mUTZk_DtlrM", verify: true },
    { id: 305, party: "UTN", cat: "politics", title: "แก้กฎหมายล้าหลัง (Guillotine)", desc: "สังคายนากฎหมายที่เป็นอุปสรรคต่อการทำมาหากินกว่า 1,000 ฉบับ", ref: "นโยบายพรรค", url: "https://unitedthaination.or.th", verify: true },
    { id: 306, party: "UTN", cat: "education", title: "เรียนฟรีถึง ป.เอก", desc: "การศึกษาเป็นการลงทุนของประเทศ ลดภาระครอบครัว สนับสนุนทุนการศึกษาชั้นสูง", ref: "กสศ.", url: "https://www.eef.or.th/", verify: true },
    { id: 307, party: "UTN", cat: "education", title: "ปลดล็อกโรงเรียน", desc: "โรงเรียนมีอิสระออกแบบการเรียนรู้ คืนครูให้นักเรียน", ref: "กสศ.", url: "https://www.eef.or.th/", verify: true },
    { id: 308, party: "UTN", cat: "economy", title: "เขตเศรษฐกิจพิเศษภาคใต้", desc: "สร้างพื้นที่เศรษฐกิจใหม่เชื่อมโยงอ่าวไทย-อันดามัน", ref: "ยุทธศาสตร์พรรค", url: "https://unitedthaination.or.th", verify: true },
    { id: 309, party: "UTN", cat: "environment", title: "กฎหมายโซลาร์เสรี", desc: "ปลดล็อกให้ประชาชนผลิตไฟฟ้าขายเข้าระบบได้จริง ลดขั้นตอนการขออนุญาต", ref: "รื้อ ลด ปลด สร้าง", url: "https://unitedthaination.or.th", verify: true },

    // --- ภูมิใจไทย (BJT) ---
    { id: 401, party: "BJT", cat: "economy", title: "พักหนี้ 3 ปี หยุดต้นปลอดดอก", desc: "พักหนี้วงเงินไม่เกิน 1 ล้านบาท เป็นเวลา 3 ปี พร้อมโครงการฝึกอาชีพปลดหนี้", ref: "นโยบายพรรค 2569", url: "https://bhumjaithai.com", verify: true },
    { id: 402, party: "BJT", cat: "social", title: "ฟรีโซล่าเซลล์", desc: "ติดตั้งโซล่าเซลล์ให้ทุกหลังคาเรือน ลดค่าไฟทันที 450 บาท/เดือน", ref: "พูดแล้วทำ Plus", url: "https://bhumjaithai.com", verify: true },
    { id: 403, party: "BJT", cat: "economy", title: "กู้ฉุกเฉิน 50,000 บาท", desc: "กองทุนเงินกู้ฉุกเฉินสำหรับประชาชน รู้ผลไว ไม่ต้องมีคนค้ำประกัน", ref: "เว็บไซต์พรรค", url: "https://bhumjaithai.com", verify: true },
    { id: 404, party: "BJT", cat: "social", title: "เครื่องฉายรังสีทุกจังหวัด", desc: "จัดหาเครื่องฉายรังสียับยั้งมะเร็งให้ครอบคลุมทุกโรงพยาบาลจังหวัด ลดการเดินทาง", ref: "นโยบายสาธารณสุข", url: "https://bhumjaithai.com", verify: true },
    { id: 405, party: "BJT", cat: "education", title: "เรียนฟรีต้องฟรีจริง", desc: "ลดภาระค่าใช้จ่ายผู้ปกครอง สนับสนุนเทคโนโลยีการศึกษา", ref: "สภาองค์กรผู้บริโภค", url: "https://www.tcc.or.th/", verify: true },
    { id: 406, party: "BJT", cat: "education", title: "เรียนออนไลน์ฟรี มีวุฒิ", desc: "ขยายโอกาสการศึกษาผ่าน Thailand Cyber University เรียนที่ไหนก็ได้", ref: "นโยบายการศึกษา", url: "https://bhumjaithai.com", verify: true },
    { id: 407, party: "BJT", cat: "economy", title: "กัญชาเพื่อสุขภาพ", desc: "สานต่อนโยบายกัญชาทางการแพทย์และเศรษฐกิจ สร้างรายได้เกษตรกร", ref: "นโยบายต่อเนื่อง", url: "https://bhumjaithai.com", verify: true },
    { id: 408, party: "BJT", cat: "economy", title: "รถเมล์ไฟฟ้าทุกจังหวัด", desc: "ขยายระบบขนส่งมวลชน EV ไปสู่หัวเมืองใหญ่ทั่วประเทศ", ref: "ผลงานคมนาคม", url: "https://bhumjaithai.com", verify: true },
    { id: 409, party: "BJT", cat: "social", title: "ฟอกไตฟรีทุกอำเภอ", desc: "จัดตั้งศูนย์ฟอกไตเทียมให้ครบทุกอำเภอ เพื่อคุณภาพชีวิตผู้ป่วย", ref: "นโยบายสาธารณสุข", url: "https://bhumjaithai.com", verify: true },
    { id: 410, party: "BJT", cat: "politics", title: "เพิ่มค่าป่วยการ อสม.", desc: "ยกระดับค่าตอบแทน อสม. เป็น 2,500 บาท/เดือน", ref: "เวทีปราศรัยใหญ่", url: "https://bhumjaithai.com", verify: true },
    { id: 411, party: "BJT", cat: "economy", title: "Wellness Tourism", desc: "ยกระดับจังหวัดท่องเที่ยวสู่เมืองสุขภาพระดับโลก ดึงดูดนักท่องเที่ยว", ref: "นโยบายเศรษฐกิจ", url: "https://bhumjaithai.com", verify: true },
    { id: 412, party: "BJT", cat: "environment", title: "มอเตอร์ไซค์ไฟฟ้าผ่อนเดือนละ 100", desc: "สนับสนุนวินมอเตอร์ไซค์และประชาชนเปลี่ยนมาใช้ EV ด้วยสินเชื่อดอกเบี้ยต่ำพิเศษ", ref: "นโยบายกรุงเทพฯ", url: "https://bhumjaithai.com", verify: true },

    // --- ประชาธิปัตย์ (DEM) ---
    { id: 501, party: "DEM", cat: "economy", title: "ประกันรายได้เกษตรกร ยุคดิจิทัล", desc: "จ่ายส่วนต่างราคาพืชผล 5 ชนิด ตรงเข้าบัญชีเกษตรกร", ref: "ยุทธศาสตร์พรรค", url: "https://democrat.or.th", verify: true },
    { id: 502, party: "DEM", cat: "politics", title: "แพลตฟอร์มส่องรัฐ", desc: "เปิดเผยข้อมูลจัดซื้อจัดจ้างให้ประชาชนตรวจสอบ เชื่อมโยงบัญชีทรัพย์สินนักการเมือง", ref: "Nation Debate", url: "https://www.youtube.com/live/mUTZk_DtlrM", verify: true },
    { id: 503, party: "DEM", cat: "education", title: "Financial Literacy", desc: "บรรจุหลักสูตรการเงินในโรงเรียน แก้ปัญหาหนี้สินคนรุ่นใหม่ระยะยาว", ref: "Nation Debate", url: "https://www.youtube.com/live/mUTZk_DtlrM", verify: true },
    { id: 504, party: "DEM", cat: "economy", title: "ธนาคารหมู่บ้าน 2 ล้าน", desc: "จัดตั้งธนาคารหมู่บ้าน/ชุมชน แห่งละ 2 ล้านบาท เป็นแหล่งทุนหมุนเวียน", ref: "ยุทธศาสตร์พรรค", url: "https://democrat.or.th", verify: true },
    { id: 505, party: "DEM", cat: "social", title: "ขจัดเลือกปฏิบัติทางเพศ", desc: "แก้ไขกฎหมายแพ่งเพื่อรองรับสิทธิของคู่รักทุกเพศอย่างเท่าเทียม", ref: "เวที Pride Vote", url: "https://www.youtube.com/playlist?list=PLR2sF1qc48QSVbFJnJbWFrUC8rsP", verify: true },
    { id: 506, party: "DEM", cat: "education", title: "เรียนจบมีงานทำ", desc: "ดึงเอกชนร่วมกำหนดหลักสูตร เน้นภาษาอังกฤษและ AI", ref: "สภาองค์กรผู้บริโภค", url: "https://www.tcc.or.th/", verify: true },
    { id: 507, party: "DEM", cat: "security", title: "Offset Policy อาวุธ", desc: "การซื้ออาวุธต้องมีการแลกเปลี่ยนสินค้าเกษตรหรือเทคโนโลยีกลับมายังประเทศ", ref: "Nation Debate", url: "https://www.youtube.com/live/mUTZk_DtlrM", verify: true },
    { id: 508, party: "DEM", cat: "security", title: "ปิดดีล FTA ยุโรป", desc: "เร่งเจรจาการค้าเสรีกับสหภาพยุโรปและตะวันออกกลางให้สำเร็จภายใน 1 ปี", ref: "ทีมเศรษฐกิจ ปชป.", url: "https://democrat.or.th", verify: true },
    { id: 509, party: "DEM", cat: "environment", title: "กฎหมายอากาศสะอาด", desc: "ผลักดัน พ.ร.บ.อากาศสะอาด ฉบับประชาชน บังคับใช้มาตรฐานมลพิษ", ref: "นโยบายสิ่งแวดล้อม", url: "https://democrat.or.th", verify: true },
    { id: 510, party: "DEM", cat: "economy", title: "SME แต้มต่อ", desc: "ให้แต้มต่อ SME ในการเข้าถึงสินเชื่อและการจัดซื้อจัดจ้างภาครัฐ", ref: "ทีมเศรษฐกิจ", url: "https://democrat.or.th", verify: true },

    // --- ประชาชาติ (PCC) ---
    { id: 601, party: "PCC", cat: "economy", title: "ล้างหนี้ กยศ. 4 ล้านคน", desc: "ยกหนี้ กยศ. ทั้งหมด (อ้างเหตุผลขัด รธน.) เพื่อปลดล็อกคนรุ่นใหม่", ref: "Nation Debate (ทวี)", url: "https://www.youtube.com/live/mUTZk_DtlrM", verify: true },
    { id: 602, party: "PCC", cat: "economy", title: "น้ำมันลิตรละ 20 บาท", desc: "ลดราคาน้ำมันดีเซลและเบนซินเหลือ 20 บาททันที โดยปรับโครงสร้างหน้าโรงกลั่น", ref: "The Standard Economic Battle", url: "https://www.youtube.com/@TheStandardNews", verify: true },
    { id: 603, party: "PCC", cat: "security", title: "พ.ร.ก. สันติภาพ", desc: "ออกกฎหมายสันติภาพชายแดนใต้ ยกเลิกกฎอัยการศึก เน้นการเจรจาพูดคุย", ref: "Nation Debate", url: "https://www.youtube.com/live/mUTZk_DtlrM", verify: true },
    { id: 604, party: "PCC", cat: "politics", title: "แก้รัฐธรรมนูญทั้งฉบับ", desc: "รื้อโครงสร้างอำนาจรัฐผ่าน สสร. ที่มาจากการเลือกตั้ง เพื่อความยุติธรรม", ref: "Matichon Real Politics", url: "https://www.youtube.com/@matichontv", verify: true },
    { id: 605, party: "PCC", cat: "education", title: "การศึกษาพหุวัฒนธรรม", desc: "ส่งเสริมการเรียนรู้ภาษาและวัฒนธรรมท้องถิ่นในโรงเรียน", ref: "ยุทธศาสตร์พรรค", url: "https://prachachat.org", verify: true },
    { id: 606, party: "PCC", cat: "economy", title: "Halal Hub World", desc: "ปั้น 3 จังหวัดชายแดนใต้เป็นศูนย์กลางอาหารฮาลาลโลก เชื่อมโยงตลาดมุสลิม", ref: "วิสัยทัศน์เศรษฐกิจ", url: "https://prachachat.org", verify: true },
    { id: 607, party: "PCC", cat: "social", title: "ยุทธศาสตร์ 0-10-100", desc: "ทุจริต 0, GDP โต 10%, ความยุติธรรม 100% เพื่อฟื้นฟูชายแดนใต้", ref: "Nation Debate", url: "https://prachachat.org", verify: true },
    { id: 608, party: "PCC", cat: "education", title: "Zero Dropout", desc: "เด็กทุกคนต้องได้เรียน ไม่มีใครหลุดจากระบบการศึกษาด้วยเหตุผลทางเศรษฐกิจ", ref: "นโยบายการศึกษา", url: "https://prachachat.org", verify: true },
    { id: 609, party: "PCC", cat: "social", title: "สวัสดิการค่าทำศพ", desc: "เงินช่วยเหลือค่าจัดการศพ 7,000 บาท สำหรับประชาชนทุกศาสนา", ref: "สวัสดิการถ้วนหน้า", url: "https://prachachat.org", verify: true },
    { id: 610, party: "PCC", cat: "education", title: "สวัสดิการครูเท่าเทียม", desc: "ยกระดับเงินเดือนและสวัสดิการครูโรงเรียนเอกชน/ปอเนาะ ให้เท่าเทียมรัฐ", ref: "นโยบายการศึกษา", url: "https://prachachat.org", verify: true },

    // --- ไทยสร้างไทย (TST) ---
    { id: 701, party: "TST", cat: "social", title: "บำนาญประชาชน 3,000 บาท", desc: "ให้ผู้สูงอายุเดือนละ 3,000 บาท เพื่อสร้างสุขภาพดีและลดภาระลูกหลาน", ref: "Thai PBS Policy Watch", url: "https://thaipbs.or.th/election69", verify: true },
    { id: 702, party: "TST", cat: "politics", title: "แขวนกฎหมาย 1,000 ฉบับ", desc: "พักการบังคับใช้ใบอนุญาตที่เป็นอุปสรรคการทำกิน 3-5 ปี ทันที", ref: "Nation Debate", url: "https://www.youtube.com/live/mUTZk_DtlrM", verify: true },
    { id: 703, party: "TST", cat: "economy", title: "กองทุน SME 3 แสนล้าน", desc: "ปล่อยกู้ SME ดอกเบี้ยต่ำ เกณฑ์พิเศษ ไม่ต้องใช้หลักทรัพย์แบบเดิม", ref: "Nation Debate", url: "https://www.youtube.com/live/mUTZk_DtlrM", verify: true },
    { id: 704, party: "TST", cat: "education", title: "จบ ป.ตรี อายุ 18", desc: "ลดเวลาเรียนลงให้จบปริญญาตรีตั้งแต่อายุ 18 ปี และเรียนฟรีจริง", ref: "Nation Debate", url: "https://www.youtube.com/live/mUTZk_DtlrM", verify: true },
    { id: 705, party: "TST", cat: "social", title: "Gender Budgeting", desc: "จัดสรรงบประมาณโดยคำนึงถึงมิติทางเพศ เพื่อความเสมอภาค", ref: "เวที Pride Vote", url: "https://www.youtube.com/playlist?list=PLR2sF1qc48QSVbFJnJbWFrUC8rsP", verify: true },
    { id: 706, party: "TST", cat: "education", title: "คูปองการศึกษา", desc: "ให้เด็กเลือกเรียนตามความถนัดผ่านระบบคูปอง", ref: "กสศ.", url: "https://www.eef.or.th/", verify: true },
    { id: 707, party: "TST", cat: "security", title: "ครัวไทยสู่ครัวโลก", desc: "ใช้ Soft Power อาหารไทยสร้างความมั่นคงทางเศรษฐกิจ", ref: "ยุทธศาสตร์พรรค", url: "https://thaisangthai.org", verify: true },
    { id: 708, party: "TST", cat: "social", title: "กองทุนพลังหญิง (Lady Future Fund)", desc: "กองทุนดอกเบี้ยต่ำ 1% สำหรับผู้หญิงและแม่เลี้ยงเดี่ยวเพื่อตั้งตัว", ref: "นโยบายสตรี", url: "https://thaisangthai.org", verify: true },
    { id: 709, party: "TST", cat: "social", title: "คูปองเลี้ยงลูก 2,000 บาท", desc: "สนับสนุนค่าเลี้ยงดูบุตร 0-6 ปี เดือนละ 2,000 บาท", ref: "นโยบายเด็ก", url: "https://thaisangthai.org", verify: true },
    { id: 710, party: "TST", cat: "economy", title: "ค่าไฟไม่เกิน 3.50 บาท", desc: "รื้อโครงสร้างพลังงาน ปรับลดค่าไฟฟ้าทันที", ref: "นโยบายพลังงาน", url: "https://thaisangthai.org", verify: true },

    // --- พลังประชารัฐ (PPRP) ---
    { id: 1701, party: "PPRP", cat: "social", title: "บัตรประชารัฐ 700+", desc: "เพิ่มวงเงินในบัตรสวัสดิการแห่งรัฐเป็น 700 บาท พร้อมประกันอุบัติเหตุ", ref: "หาเสียงโค้งสุดท้าย", url: "https://pprp.or.th", verify: true },
    { id: 1702, party: "PPRP", cat: "social", title: "เบี้ยผู้สูงอายุขั้นบันได", desc: "60 ปีรับ 600, 70 ปีรับ 800, 80 ปีรับ 1,000 บาท", ref: "นโยบายพรรค", url: "https://pprp.or.th", verify: true },
    { id: 1703, party: "PPRP", cat: "economy", title: "น้ำมันประชาชน", desc: "ลดราคาน้ำมันเบนซินและดีเซลเพื่อลดต้นทุนค่าครองชีพ", ref: "นโยบายพรรค", url: "https://pprp.or.th", verify: true },
    { id: 1704, party: "PPRP", cat: "education", title: "เรียนภาษาอังกฤษ-จีนฟรี", desc: "เรียนกับเจ้าของภาษา สัปดาห์ละ 2 คาบ ตั้งแต่ประถม", ref: "Dek-D", url: "https://pprp.or.th", verify: true },
    { id: 1705, party: "PPRP", cat: "environment", title: "มีเราไม่มีแล้ง", desc: "บริหารจัดการน้ำชุมชนครบวงจร เพิ่มพื้นที่ชลประทาน", ref: "ผลงาน พล.อ.ประวิตร", url: "https://pprp.or.th", verify: true },
    { id: 1706, party: "PPRP", cat: "economy", title: "กองทุนหมู่บ้านประชารัฐ", desc: "อัดฉีดเม็ดเงินลงกองทุนหมู่บ้าน 3 แสนล้านบาท", ref: "นโยบายเศรษฐกิจ", url: "https://pprp.or.th", verify: true },
    { id: 1707, party: "PPRP", cat: "social", title: "ที่ดินทำกินมั่นคง", desc: "เปลี่ยน ส.ป.ก. เป็นโฉนดเพื่อเกษตรกรรม (สานต่อนโยบาย)", ref: "ยุทธศาสตร์พรรค", url: "https://pprp.or.th", verify: true },
    { id: 1708, party: "PPRP", cat: "security", title: "รั้วชายแดนมั่นคง", desc: "สร้างรั้วและระบบเฝ้าระวังตลอดแนวชายแดน ป้องกันยาเสพติดและสิ่งผิดกฎหมาย", ref: "นโยบายความมั่นคง", url: "https://pprp.or.th", verify: true },
    { id: 1709, party: "PPRP", cat: "politics", title: "กวาดล้างทุนสีเทา", desc: "ปราบปรามมาเฟียข้ามชาติและแก๊งคอลเซ็นเตอร์อย่างเด็ดขาด", ref: "ยุทธศาสตร์พรรค", url: "https://pprp.or.th", verify: true },

    // --- เศรษฐกิจ (SET) - NEW ---
    { id: 1801, party: "SET", cat: "economy", title: "เศรษฐกิจฐานราก", desc: "พัฒนาเศรษฐกิจฐานรากด้วยนโยบายเชิงโครงสร้าง เพิ่มรายได้ชุมชน", ref: "นโยบายพรรค", url: "#", verify: false },
    { id: 1802, party: "SET", cat: "economy", title: "ลดต้นทุนพลังงาน", desc: "ปรับโครงสร้างพลังงานเพื่อลดต้นทุนการผลิตและค่าครองชีพ", ref: "นโยบายพรรค", url: "#", verify: false },
    { id: 1803, party: "SET", cat: "economy", title: "ส่งเสริมการลงทุน SME", desc: "สร้างกลไกสนับสนุน SME ด้วยสินเชื่อดอกเบี้ยต่ำและลดกฎระเบียบ", ref: "นโยบายพรรค", url: "#", verify: false },

    // --- เสรีรวมไทย (SRT) - NEW ---
    { id: 1901, party: "SRT", cat: "politics", title: "ปฏิรูปกองทัพถอนรากถอนโคน", desc: "ปฏิรูปกองทัพทั้งระบบ ยกเลิกเกณฑ์ทหาร ลดงบกลาโหม", ref: "นโยบายพรรค", url: "#", verify: false },
    { id: 1902, party: "SRT", cat: "politics", title: "ปราบคอร์รัปชันเด็ดขาด", desc: "เพิ่มโทษทุจริต ยึดทรัพย์ถาวร เปิดเผยข้อมูลรัฐทั้งหมด", ref: "นโยบายพรรค", url: "#", verify: false },
    { id: 1903, party: "SRT", cat: "social", title: "เสรีภาพประชาชน", desc: "ปลดล็อกเสรีภาพในการแสดงออก ยกเลิกกฎหมายที่จำกัดสิทธิประชาชน", ref: "นโยบายพรรค", url: "#", verify: false },

    // --- พรรคเล็กอื่นๆ (OTH) - policies from former CTP, TKM, OKM ---
    { id: 2001, party: "OTH", cat: "economy", title: "Green Economy", desc: "สร้างรายได้จากการขายคาร์บอนเครดิตภาคเกษตร", ref: "WoW Thailand", url: "#", verify: false },
    { id: 2002, party: "OTH", cat: "social", title: "น้ำบาดาลทุกตำบล", desc: "เจาะน้ำบาดาลขนาดใหญ่แก้ภัยแล้ง มีน้ำประปาสะอาดทุกหมู่บ้าน", ref: "นโยบายพรรค", url: "#", verify: false },
    { id: 2003, party: "OTH", cat: "politics", title: "Single Command ภัยพิบัติ", desc: "นายกฯ สั่งการภัยพิบัติด้วยตัวเอง บูรณาการข้อมูลดาวเทียม THEOS-2", ref: "Nation Debate", url: "#", verify: false },
    { id: 2004, party: "OTH", cat: "security", title: "ปราบสแกมเมอร์ใน 60 วัน", desc: "ใช้เทคโนโลยีบล็อกบัญชีม้าและเส้นทางการเงินผิดกฎหมายภายใน 2 เดือน", ref: "Nation Debate", url: "#", verify: false },
    { id: 2005, party: "OTH", cat: "education", title: "AI ในห้องเรียน", desc: "นำ AI มาช่วยครูสอนและวิเคราะห์พัฒนาการเด็กรายบุคคล", ref: "วิสัยทัศน์ ดร.เอ้", url: "#", verify: false },
    { id: 2006, party: "OTH", cat: "economy", title: "อัดฉีดงบ 5 แสนล้าน", desc: "เร่งรัดงบลงทุนค้างท่อ 5 แสนล้านบาทเข้าระบบภายในไตรมาส 2 เพื่อจ้างงานท้องถิ่น", ref: "Nation Debate", url: "#", verify: false },
    { id: 2007, party: "OTH", cat: "environment", title: "Carbon Credit Hub", desc: "ผลักดันไทยเป็นศูนย์กลางซื้อขายคาร์บอนเครดิตแห่งอาเซียน", ref: "นโยบายสิ่งแวดล้อม", url: "#", verify: false },
    { id: 2008, party: "OTH", cat: "social", title: "เมืองอารยสถาปัตย์", desc: "ปรับปรุงเมืองให้รองรับผู้สูงอายุและคนพิการ (Universal Design)", ref: "นโยบายพรรค", url: "#", verify: false },
];
